// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiqaMGG-0Cyw1quBAeu7qYmLhzb78AdKE',
    appId: '1:231818879705:web:76b429fe78811a601e54c8',
    messagingSenderId: '231818879705',
    projectId: 'flutter-training-app-46c4a',
    authDomain: 'flutter-training-app-46c4a.firebaseapp.com',
    databaseURL: 'https://flutter-training-app-46c4a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-training-app-46c4a.firebasestorage.app',
    measurementId: 'G-SH03CJNE88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB64PLMZhrbyKD4_1sBDX1wckzo7XU0fuw',
    appId: '1:231818879705:android:0959676d11e34e581e54c8',
    messagingSenderId: '231818879705',
    projectId: 'flutter-training-app-46c4a',
    databaseURL: 'https://flutter-training-app-46c4a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-training-app-46c4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYJv16GN0r_TbfdjrXIFXwRVwjUd5Rruc',
    appId: '1:231818879705:ios:6a024eed1b5a81451e54c8',
    messagingSenderId: '231818879705',
    projectId: 'flutter-training-app-46c4a',
    databaseURL: 'https://flutter-training-app-46c4a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-training-app-46c4a.firebasestorage.app',
    iosBundleId: 'com.training.taskflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYJv16GN0r_TbfdjrXIFXwRVwjUd5Rruc',
    appId: '1:231818879705:ios:388754a511ff26251e54c8',
    messagingSenderId: '231818879705',
    projectId: 'flutter-training-app-46c4a',
    databaseURL: 'https://flutter-training-app-46c4a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-training-app-46c4a.firebasestorage.app',
    iosBundleId: 'com.example.taskFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiqaMGG-0Cyw1quBAeu7qYmLhzb78AdKE',
    appId: '1:231818879705:web:ff706447a5330a171e54c8',
    messagingSenderId: '231818879705',
    projectId: 'flutter-training-app-46c4a',
    authDomain: 'flutter-training-app-46c4a.firebaseapp.com',
    databaseURL: 'https://flutter-training-app-46c4a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-training-app-46c4a.firebasestorage.app',
    measurementId: 'G-BWC01M2982',
  );
}
